#ifndef DOORCTL_MBEDTLS_CONFIG_H
#define DOORCTL_MBEDTLS_CONFIG_H

#define MBEDTLS_SHA256_C
#define MBEDTLS_BASE64_C

#define MBEDTLS_BIGNUM_C
#define MBEDTLS_ECP_C

#define MBEDTLS_ECP_DP_SECP256R1_ENABLED
#define MBEDTLS_ECP_NIST_OPTIM
#define MBEDTLS_ASN1_WRITE_C
#define MBEDTLS_ASN1_PARSE_C
#define MBEDTLS_ASN1_PARSE_C
#define MBEDTLS_ECDSA_C

#endif //DOORCTL_MBEDTLS_CONFIG_H